//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Livraria.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Livro
    {
        public int Id { get; set; }
        public string Titulo { get; set; }
        public string Subtitulo { get; set; }
        public byte Edicao { get; set; }
        public int Ano { get; set; }
        public int Paginas { get; set; }
        public double Preco { get; set; }
        public string Editora { get; set; }
        public byte Idioma { get; set; }
    }
}
